
soullifiedlifesoundtrack_homepage:
    pattern:  /my-life-soundtrack/{username}
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:showHomePage }

soullifiedlifesoundtrack_homepage_angular:
    pattern:  /soundtrack/angular
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:showHomePageAngular }

soullifiedlifesoundtrack_search_lyrics:
    pattern:  /getLyrics/getLyrics
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:getLyrics }


soullifiedlifesoundtrack_add_track:
    pattern:  /add/track
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:addSong }

soullifiedlifesoundtrack_get_full_lyrics:
    pattern:  /getLyrics/getfull
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:getFullLyrics }

soullifiedlifesoundtrack_update_chosen_lyrics:
    pattern:  /update/lyrics
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:updateLyrics }

soullifiedlifesoundtrack_get_next_wave:
    pattern:  /getnext/wave
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:getNextWave }

soullifiedlifesoundtrack_get_angular_tracks:
    pattern:  /getangular/tracks
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:getSoundtrackAngular }

soullifiedlifesoundtrack_gen_new_editId:
    pattern:  /gen/editId
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:generateEditId }

soullifiedlifesoundtrack_add_new_comment:
    pattern:  /commenttrack/add
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:addComment }

soullifiedlifesoundtrack_delete_comment:
    pattern:  /commenttrack/delete
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:deleteComment }

soullifiedlifesoundtrack_upload_photo_comment:
    pattern:  /commenttrack/upload
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:upload }

soullifiedlifesoundtrack_update_Full_lyrics:
    pattern:  /soundtrack/setFullLyrics
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:updateFullLyrics }

soullifiedlifesoundtrack_get_Full_lyrics_ready:
    pattern:  /soundtrack/readygetfulllyrics
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:getFullLyricsReady }

soullifiedlifesoundtrack_update_youtube_id:
    pattern:  /soundtrack/updateYoutubeId
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:updateYoutubeId }

update_lifesoundtrack_background:
    pattern:  /soundtrack/updatebackground
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:setLifesoundtrackPredefinedBackground }

confirm_upload_track_photo:
    pattern:  /soundtrack/confitmuploadphoto
    defaults: { _controller: soullifiedlifesoundtrackBundle:lifesoundtrack:saveTrackBackground }