parameters:
#    soullifiedlifesoundtrack.example.class: soullified\lifesoundtrackBundle\Example

services:
#    soullifiedlifesoundtrack.example:
#        class: %soullifiedlifesoundtrack.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
