fos_user_registration_register:
    pattern:    /register
    defaults: {_controller:FOSUserBundle:Registration:register}
    
fos_user_registration_confirm:
    pattern:    /check-email
    defaults: {_controller:FOSUserBundle:Registration:checkEmail}

fos_user_registration_confirmed:
    pattern:    /confirmed
    defaults: {_controller:FOSUserBundle:Registration:confirmed}

fos_user_security_login:
    pattern:    /login
    defaults: {_controller:FOSUserBundle:Security:login}

fos_user_security_check:
    pattern:    /login_check
    defaults: {_controller:FOSUserBundle:Security:check}

fos_user_security_logout:
    pattern:    /logout
    defaults: {_controller:FOSUserBundle:Security:logout}
    
# fos_user_profile_show:
#     pattern:    /
#     defaults: {_controller:FOSUserBundle:Profile:show}

fos_user_profile_edit_profil:
    pattern:    /edit
    defaults: {_controller:FOSUserBundle:Profile:edit}

# <route id="fos_user_profile_show" pattern="/">
#     <default key="_controller">FOSUserBundle:Profile:show</default>
#     <requirement key="_method">GET</requirement>
# </route>

# <route id="fos_user_profile_edit" pattern="/edit">
#     <default key="_controller">FOSUserBundle:Profile:edit</default>
# </route>



#requirementkey get




    # <route id="fos_user_registration_register" pattern="/">
    #     <default key="_controller">FOSUserBundle:Registration:register</default>
    # </route>

    # <route id="fos_user_registration_check_email" pattern="/check-email">
    #     <default key="_controller">FOSUserBundle:Registration:checkEmail</default>
    #     <requirement key="_method">GET</requirement>
    # </route>

    # <route id="fos_user_registration_confirm" pattern="/confirm/{token}">
    #     <default key="_controller">FOSUserBundle:Registration:confirm</default>
    #     <requirement key="_method">GET</requirement>
    # </route>

    # <route id="fos_user_registration_confirmed" pattern="/confirmed">
    #     <default key="_controller">FOSUserBundle:Registration:confirmed</default>
    #     <requirement key="_method">GET</requirement>
    # </route>