parameters:
#    soullified_user.example.class: soullified\UserBundle\Example

services:
#    soullified_user.example:
#        class: %soullified_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]



parameters:
    my_user_provider.class: soullified\UserBundle\Security\Core\User\FOSUBUserProvider
 
services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{ google : google_id, facebook: facebook_id}, @doctrine.orm.entity_manager ]